// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNGrnhObw1wCpnBGipvuY-oAwCyfwfsQ',
    appId: '1:58735476746:web:4383b08c6a8fcb78009ff3',
    messagingSenderId: '58735476746',
    projectId: 'learn-flutter-68-2-7a589',
    authDomain: 'learn-flutter-68-2-7a589.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2-7a589.firebasestorage.app',
    measurementId: 'G-QTG250GFFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfrgjEgyv5vxIt_Rs_5pVTiO0QS2ksVXg',
    appId: '1:58735476746:android:6de4902594095e61009ff3',
    messagingSenderId: '58735476746',
    projectId: 'learn-flutter-68-2-7a589',
    storageBucket: 'learn-flutter-68-2-7a589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdFfFT598xrhIUMoFVCDhUrJXdZ5rEiw',
    appId: '1:58735476746:ios:7028c99d28478368009ff3',
    messagingSenderId: '58735476746',
    projectId: 'learn-flutter-68-2-7a589',
    storageBucket: 'learn-flutter-68-2-7a589.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxdFfFT598xrhIUMoFVCDhUrJXdZ5rEiw',
    appId: '1:58735476746:ios:7028c99d28478368009ff3',
    messagingSenderId: '58735476746',
    projectId: 'learn-flutter-68-2-7a589',
    storageBucket: 'learn-flutter-68-2-7a589.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYNGrnhObw1wCpnBGipvuY-oAwCyfwfsQ',
    appId: '1:58735476746:web:f53daab4811f0ae8009ff3',
    messagingSenderId: '58735476746',
    projectId: 'learn-flutter-68-2-7a589',
    authDomain: 'learn-flutter-68-2-7a589.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2-7a589.firebasestorage.app',
    measurementId: 'G-LPN70XK4N5',
  );
}
